# config.yaml
name: "ha ssh proxy tunnel"
slug: "ha_ssh_proxy_tunnel"
description: "Addon permettant d'ouvrir un tunnel SSH avec proxy SOCKS, de limiter l'accès par IP et de gérer l'authentification par mot de passe ou clé RSA."
version: "2025.0.13-alpha"
maintainer: "echavet@gmail.com"
url: "https://github.com/echavet/ha_ssh_proxy_tunnel"

init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  
privileged:
  - NET_ADMIN
  #- SYS_ADMIN
  #- SYS_RAWIO
  #- SYS_TIME
  #- SYS_NICE
  
map:
  - ssh_keys:rw
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
  
options:
  allowed_ips: "127.0.0.1"
  ssh_target: "user@mydomain.com"
  ssh_port: 22
  ssh_password: ""    
  tunnel_listen_address: "192.168.1.x"
  tunnel_listen_port: 3000
  key_algo: "rsa"
        
  key_length: 3072
  key_passphrase: ""
    

schema:
  allowed_ips: str
  ssh_target: str
  ssh_port: int
  ssh_password: password?
  key_algo: list(dsa|ecdsa|ecdsa-sk|ed25519|ed25519-sk|rsa)
  key_length: int
  key_passphrase: password?
  tunnel_listen_address: str
  tunnel_listen_port: int
