# config.yaml
name: "ha ssh proxy tunnel"
slug: "ha_ssh_proxy_tunnel"
description: "Addon permettant d'ouvrir un tunnel SSH avec proxy SOCKS, de limiter l'accès par IP et de gérer l'authentification par mot de passe ou clé RSA."
version: "2025.2.2-beta-1.3"
maintainer: "echavet@gmail.com"
url: "https://github.com/echavet/ha_ssh_proxy_tunnel"

init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  
privileged:
  - NET_ADMIN  
  
map:
  - ssh_keys:rw
  - addons:r
  - homeassistant_config:rw  
  - share:rw
  - ssl:rw

host_network: true

ports:
  80/tcp: 3001
ports_description:
  80/tcp: Tunnel Listen Port
  
options:
  allowed_ips: "127.0.0.1"
  ssh_target: "user@mydomain.com"
  ssh_port: 22
  ssh_password: ""    
  tunnel_listen_address: "0.0.0.0"
  #tunnel_listen_port: 3001
  key_algo: "rsa"
        
  key_length: 3072
  key_passphrase: ""
  debug: false

schema:
  allowed_ips: str
  ssh_target: str
  ssh_port: int
  ssh_password: password?
  key_algo: list(dsa|ecdsa|ecdsa-sk|ed25519|ed25519-sk|rsa)
  key_length: int
  key_passphrase: password?
  tunnel_listen_address: str
  debug: bool
  #tunnel_listen_port: int
