# config.yaml
name: "ha ssh proxy tunnel"
slug: "ha_ssh_proxy_tunnel"
description: "Addon permettant d'ouvrir un tunnel SSH avec proxy SOCKS, de limiter l'accès par IP et de gérer l'authentification par mot de passe ou clé RSA."
version: "2025.0.9-alpha"
maintainer: "echavet@gmail.com"
url: "https://github.com/echavet/ha_ssh_proxy_tunnel"

init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  
options:
  allowed_ips:
    description: "Liste des IP autorisées (séparées par des virgules)"
    default: "127.0.0.1"
  ssh_target:
    description: "Destination SSH (format user@host)"
    default: "user@mydomain.com"
  ssh_port:
    description: "Port SSH de la destination"
    default: 22
  ssh_password:
    description: "Mot de passe SSH (laisser vide si utilisation d'une clé RSA)"
    default: ""
  authorized_keys:
    description: "Contenu complet de la clé RSA (clé privée) à utiliser pour l'authentification"
    default: []
  tunnel_listen_address:
    description: "Adresse d'écoute du tunnel"
    default: "192.168.1.x"
  tunnel_listen_port:
    description: "Port d'écoute du tunnel"
    default: 3000

schema:
  allowed_ips: str
  ssh_target: str
  ssh_port: int
  ssh_password: password
  authorized_key: str
  tunnel_listen_address: str
  tunnel_listen_port: int
