# config.yaml
name: "ha ssh proxy tunnel"
slug: "ha_ssh_proxy_tunnel"
description: "Addon permettant d'ouvrir un tunnel SSH avec proxy SOCKS, de limiter l'accès par IP et de gérer l'authentification par mot de passe ou clé RSA."
version: "2025.0.10-alpha"
maintainer: "echavet@gmail.com"
url: "https://github.com/echavet/ha_ssh_proxy_tunnel"

init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  
privileged:
  - NET_ADMIN
  #- SYS_ADMIN
  #- SYS_RAWIO
  #- SYS_TIME
  #- SYS_NICE
  
options:
  allowed_ips:
    description: "Liste des IP autorisées (séparées par des virgules)"
    default: "127.0.0.1"
  ssh_target:
    description: "Destination SSH (format user@host)"
    default: "user@mydomain.com"
  ssh_port:
    description: "Port SSH de la destination"
    default: 22
  ssh_password:
    description: "Mot de passe SSH (laisser vide si utilisation d'une clé RSA)"
    default: "secret"  
  tunnel_listen_address:
    description: "Adresse d'écoute du tunnel"
    default: "192.168.1.x"
  tunnel_listen_port:
    description: "Port d'écoute du tunnel"
    default: 3000
  key_algo:
    description: "Algorithme pour la génération de la clé (dsa | ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa)"
    default: "rsa"
  key_length:
    description: "Longueur de la clé (applicable pour rsa, dsa, ecdsa)"
    default: 3072
  key_passphrase:
    description: "Passphrase pour protéger la clé SSH générée (laisser vide pour aucune passphrase)"
    default: "ha_ssh_proxy_tunnel"

schema:
  allowed_ips: str
  ssh_target: str
  ssh_port: int
  ssh_password: password
  key_algo: str
  key_length: int
  key_passphrase: password
  tunnel_listen_address: str
  tunnel_listen_port: int
